// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use diesel::Queryable;
use serde::Serialize;

#[derive(Queryable, Debug, Serialize)]
pub struct Collection {
    pub id: i32,
    pub collection_name: String,
    pub ceiling_price: i32,
    pub active_trades: i32,
    pub total_trades: i32,
    pub volume: i32,
    pub supply: i32,
}

#[derive(Queryable, Debug, Serialize)]
pub struct Order {
    pub id: i32,
    pub trade_id: i32,
    pub collection_id: i32,
    pub user_id: i32,
    pub trade_amount: i32,
    pub rarity: String,
    pub collection_root: String,
}

#[derive(Queryable, Debug, Serialize)]
pub struct Trade {
    pub id: i32,
    pub collection_id: i32,
    pub user_id: i32,
    pub accepted: bool,
    pub accepted_order_id: Option<i32>,
    pub buyer_address: Vec<u8>,
    pub seller_address: Option<Vec<u8>>,
    pub deposited_amount: i32,
}

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: i32,
    pub address: String,
    pub user_name: String,
}

